name: Flutter CI

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get

      #- run: flutter analyze


    timeout-minutes: 10

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build apk --flavor prod -t lib/main.dart --release
      - run: flutter build apk --flavor dev -t lib/debug_main.dart --release
    timeout-minutes: 10
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk lib/main.dart --release

      - name: upload apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: '1:887278312984:android:7938280b0a22a0526dad6d'
          token: '1//0catZdI_T4lP5CgYIARAAGAwSNwF-L9IrFNvFVfTE2pJvGYuUL4cgVVvNzbPjL0MZJCeS4V-9hxdxm-MdKvXvlTSf5QulVyNVv34'
          groups: testers
          file: build/app/outputs/apk/release/app-release.apk